### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by wallrj**
Fixed a couple of typos in the README

### CODE REVIEW

**Comment by simplyzee** [comment]
> Fixed a couple of typos in the README

Thanks @wallrj 
Could you sign the commit otherwise it all looks good to me 🙂

**Comment by munnerz** [comment]
Requires either Zee or Wil to approve 😄 

/lgtm
/assign @zee-ahmed @wwwil

**Comment by munnerz** [comment]
Test failures seem unrelated - I've opened #50 to track 😄

**Review by simplyzee — APPROVED** [review]
/lgtm

Thanks @munnerz for checking and looking into the PR tests. I agree, they're unrelated :smile:

**Pull request merged**
